### PR TITLE
Fix pin change interrupts

### PR DESCRIPTION
**Pull request by mjbrown**
With a little behind the scenes code it also allows the user to have an independent interrupt for every digital pin, even though the micro controller only supports 3 interrupts.

### CODE REVIEW

**Comment by raykamp** [comment]
@mjbrown, awesome work on this! Couple of things:
Has this been tested when used alongside the SoftwareSerial library which also makes use of the same interrupt vectors?

The example sketches in this repo are no longer used, and have been kept for legacy purposes. I'd think they can be removed by now.
The example sketch repo can be found here: https://github.com/PunchThrough/Arduino-IDE-examples
Please follow the general style of the other sketches. Please mark Simone and/or myself as reviewers for the example sketch.

**Comment by raykamp** [comment]
Below is the sketch that I'm using to test: 

```
#include <SoftwareSerial.h>
SoftwareSerial mySerial(4, 5); // RX, TX

void setup() {
  Bean.setLed(0, 0, 0);
  mySerial.begin(4800);
}

void loop() {

}
```

**Comment by mjbrown** [comment]
My code definitely breaks that.  This will be a tough problem to solve.  The AVR builds in a file which contains all of the ISRs weakly defined to jump to the reset vector.  Unfortunately, this means that if I weakly define the ISRs they will be ignored, since the compiler doesn't care about repeated weak definitions.  I cannot make our file link first either.  It also means that an "ifndef" won't work, because it IS defined.  When I strongly define them as I have, they will clash with SoftwareSerial or any other library.  I'm going to look into adding an include which defines them, so that people have to exclusively choose the bean interface or something else.

**Comment by mjbrown** [comment]
http://playground.arduino.cc/Main/PinChangeInt

This library accomplishes all of the functionality fixed by this PR.  I'm going to delete all of our change interrupt code in favor of directing users towards the existing library which works across different Arduino hardware.  This also saves the effort of updating this code on future devices.

**Comment by mjbrown** [comment]
Verified this works on both the Bean and Bean+ for the first six digital pins.

**Pull request closed without merging**
